# Generated by Django 5.2.1 on 2026-04-06 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('house', models.CharField(max_length=20, verbose_name='House')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='Apartment')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Post code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address to delivery',
                'verbose_name_plural': 'Addresses to delivery',
                'ordering': ['-is_default', 'city', 'street'],
            },
        ),
    ]
