[pytest]
DJANGO_SETTINGS_MODULE = Test_task.settings

# Pytest будет искать тесты в файлах tests.py в каждом приложении
python_files = tests.py test_*.py *_test.py

pythonpath = .

# Добавляем маркеры
markers =
    slow: marks tests as slow
    unit: unit tests
    integration: integration tests
    api: API tests

# Настройки вывода
addopts =
    --verbose
    --strict-markers
    --tb=short
    --cov=apps
    --cov-report=html
    --cov-report=term-missing