# Generated by Django 5.2.1 on 2026-04-05 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_seller_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exist', models.BooleanField(default=False)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='favorites.favorite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Детали списка избранных',
                'verbose_name_plural': 'Детали списков избранных',
                'unique_together': {('favorite', 'product')},
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', through='favorites.FavoriteItem', through_fields=('favorite', 'product'), to='products.product'),
        ),
    ]
