# Generated by Django 5.2.1 on 2026-04-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('seller', 'Продавец'), ('admin', 'Администратор')], default='user', max_length=6),
        ),
    ]
