# Generated by Django 5.2.1 on 2026-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Создан'), ('paid', 'Оплачен'), ('in_delivery', 'Отправлен'), ('completed', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=16),
        ),
    ]
