# Generated by Django 5.2.1 on 2026-04-15 17:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_products_ca_name_693421_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'Истории цен',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='products_pr_product_429236_idx')],
            },
        ),
    ]
